/-
Copyright (c) 2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CC.MPC

/-!
# The fixed-`Z` CC judgment as a LiuMau20 specification family

`CC.SecurelyConstructs Z simulators protocol bottom ε R S` (MauRen11 §5.1
Definition 3) fixes **one** dishonest set `Z` and names **one** simulator.
LiuMau20 §2.4 Definition 1 instead states one construction per dishonest set,

  `∀ Z ⊆ P.  R_Z —π^{P∖Z}→ S_Z`,

restricted to an adversary structure `𝒵`
(`AbstractCrypto.ConstructsForAdversaryStructure`), and LiuMau20 §2.5 replaces
the named simulator by the `∗Z`-relaxed ideal specification
`AbstractCrypto.zStar tupleGamma Z`.  This module is the bridge between the
two, for the corruption pattern the CC endpoints of this repository actually
use: **one** dishonest interface `e` (`Interface.eve` throughout
`RandomSystemsCC/Symmetric/`).

## What the two forms say, side by side

Definition 3's two clauses are *not* two halves of one construction: they are
the two rungs of the LiuMau20 family for the adversary structure generated by
`{e}`, once the availability filter `⊥` is read as the honest-`e` converter
and moved into the protocol tuple `π = protocol * bottom`:

| dishonest set `Z` | honest attachment `π ⇂ Zᶜ` | rung |
| --- | --- | --- |
| `∅` | `protocol * bottom` | availability |
| `{e}` | `protocol` | security |

Correspondingly the ideal family is `Z ↦ (({⊥ ⇂ Zᶜ • S})∗Z)ᵋ`: at `Z = ∅` the
filter survives and the `∗`-relaxation collapses, giving Definition 3's
`⊥ᶻ S`; at `Z = {e}` the filter disappears and the relaxation supplies the
simulator, giving Definition 3's `σᶻ S` without naming `σ` in the statement.

The `ᵋ` is separable, which Definition 3's is not: a construction whose leaves
are literal equalities gets the family *without* any `eball`, on a carrier
with no `PseudoEMetricSpace` instance at all
(`constructsForAdversaryStructure_of_exact_leaves`), and the relaxation is
applied afterwards as a separate weakening
(`constructsForAdversaryStructure_eball_of_exact`).

## Why the structure is generated by a *singleton*

`AbstractCrypto.AdversaryStructure` is monotone (LiuMau20 §8, fn. 8), so the
smallest structure containing `Z` is its full downward closure.  A fixed-`Z`
judgment carries no information at the intermediate sets `∅ ⊊ Z' ⊊ Z`, so it
can only ever be lifted to a structure whose non-trivial rungs it actually
covers — that is, `{Z' | Z' ⊆ {e}} = {∅, {e}}`.  This is a genuine limit of
Definition 3, not of the translation: with more than one dishonest interface
the fixed-`Z` statement simply does not say what happens when a strict subset
is corrupted.

## References

* [U. Maurer, *Constructive Cryptography — A New Paradigm for Security
  Definitions and Proofs*, TOSCA 2011][MauRen11], §5.1 Definition 3.
* [C.-D. Liu-Zhang, U. Maurer, *Synchronous Constructive Cryptography*,
  TCC 2020][LiuMau20], §2.4 Definition 1, §2.5, §8.
-/

namespace RandomSystemsCC

open AbstractCrypto
open scoped ENNReal

universe u v w

variable {I : Type u} {Γ : I → Type v} {Φ : Type w}
variable [∀ i, Monoid (Γ i)] [MulAction (∀ i, Γ i) Φ]

/-! ## Pattern-attachment receipts

Three small facts about `patternAttach` at a singleton pattern and its
complement.  They are what turns Definition 3's `π ⇂ Zᶜ` / `⊥ ⇂ Z` into the
bare tuples the resource-level proofs produce. -/

/-- Attaching along the whole interface set changes nothing. -/
theorem patternAttach_univ (f : ∀ i, Γ i) :
    patternAttach (Set.univ : Set I) f = f := by
  funext i
  exact patternAttach_apply_of_mem f (Set.mem_univ i)

/-- A tuple already trivial outside `P` is unchanged by attachment at `P`. -/
theorem patternAttach_eq_self {P : Set I} {f : ∀ i, Γ i}
    (h : ∀ i ∉ P, f i = 1) : patternAttach P f = f := by
  funext i
  by_cases hi : i ∈ P
  · exact patternAttach_apply_of_mem f hi
  · rw [patternAttach_apply_of_notMem f hi]
    exact (h i hi).symm

/-- A tuple trivial inside `P` is annihilated by attachment at `P`. -/
theorem patternAttach_eq_one {P : Set I} {f : ∀ i, Γ i}
    (h : ∀ i ∈ P, f i = 1) : patternAttach P f = 1 := by
  funext i
  by_cases hi : i ∈ P
  · rw [patternAttach_apply_of_mem f hi, h i hi]
    rfl
  · rw [patternAttach_apply_of_notMem f hi]
    rfl

/-- The honest attachment of a protocol that leaves the dishonest interface
alone is the protocol itself. -/
theorem patternAttach_compl_singleton_eq_self {e : I} {protocol : ∀ i, Γ i}
    (h : protocol e = 1) :
    patternAttach ({e} : Set I)ᶜ protocol = protocol :=
  patternAttach_eq_self fun i hi => by
    rw [Set.notMem_compl_iff, Set.mem_singleton_iff] at hi
    exact hi ▸ h

/-- The availability filter, supported at the dishonest interface, is
unchanged by attachment there. -/
theorem patternAttach_singleton_eq_self {e : I} {bottom : ∀ i, Γ i}
    (h : ∀ i, i ≠ e → bottom i = 1) :
    patternAttach ({e} : Set I) bottom = bottom :=
  patternAttach_eq_self fun i hi => h i (by simpa using hi)

/-- …and is annihilated by attachment at the honest interfaces. -/
theorem patternAttach_compl_singleton_eq_one {e : I} {bottom : ∀ i, Γ i}
    (h : ∀ i, i ≠ e → bottom i = 1) :
    patternAttach ({e} : Set I)ᶜ bottom = 1 :=
  patternAttach_eq_one fun i hi => h i (by simpa using hi)

/-! ## `∗Z` at the empty dishonest set

With nobody corrupted the joint dishonest class is trivial and the
`∗`-relaxation collapses; this is what makes the `Z = ∅` rung read as
Definition 3's availability clause rather than as a relaxed statement. -/

/-- The joint dishonest converter class of the empty set is trivial. -/
theorem zSub_empty {M : Type*} [Monoid M] (γ : I → Submonoid M) :
    zSub γ (∅ : Set I) = ⊥ :=
  iSup_of_empty _

/-- `∗∅` is the identity relaxation. -/
theorem zStar_empty {M : Type*} [Monoid M] [MulAction M Φ]
    (γ : I → Submonoid M) (X : Set Φ) :
    zStar γ (∅ : Set I) X = X := by
  ext x
  constructor
  · rintro ⟨σ, hσ, r, hr, rfl⟩
    rw [zSub_empty] at hσ
    have hone : σ = 1 := Submonoid.mem_bot.mp hσ
    subst hone
    simpa using hr
  · intro hx
    exact ⟨1, one_mem _, x, hx, one_smul M x⟩

/-! ## The adversary structure generated by one dishonest interface -/

/-- The adversary structure tolerated by a fixed-`Z` CC statement with
`Z = {e}`: the downward closure `{Z' | Z' ⊆ {e}} = {∅, {e}}`.  Monotonicity
(LiuMau20 §8 fn. 8) is transitivity of `⊆`. -/
def singleDishonest (e : I) : AdversaryStructure I where
  sets := {Z | Z ⊆ ({e} : Set I)}
  mono h hZ := h.trans hZ

@[simp] theorem mem_singleDishonest {e : I} {Z : Set I} :
    Z ∈ (singleDishonest e).sets ↔ Z ⊆ ({e} : Set I) := Iff.rfl

theorem empty_mem_singleDishonest (e : I) :
    (∅ : Set I) ∈ (singleDishonest e).sets :=
  mem_singleDishonest.mpr (Set.empty_subset _)

theorem singleton_mem_singleDishonest (e : I) :
    ({e} : Set I) ∈ (singleDishonest e).sets :=
  mem_singleDishonest.mpr subset_rfl

/-! ## The specification-form statement and the two bridges -/

open Classical in
/-- **The exact LiuMau20 specification-form construction, from its two
resource-level equations.**

This is the shape `CC.SecurelyConstructs` structurally *cannot* express: it
asserts set containment, not a distance bound, and it needs no
`PseudoEMetricSpace` instance at all.  On a pseudo-emetric carrier the
zero-radius ball around a specification can be strictly larger than the
specification, so an endpoint whose proof produces literal equalities — as the
perfect symmetric constructions do — loses information by stating itself with
`ε = 0`.  JM20 §2.3's point exactly: the relaxation is a separate, optional
layer, applied by `constructsForAdversaryStructure_eball_of_exact` when a
statement genuinely needs it. -/
theorem constructsForAdversaryStructure_of_exact_leaves
    {e : I} {protocol bottom : ∀ i, Γ i} {R S : Φ}
    (hprotocol : protocol e = 1)
    (hbottom : ∀ i, i ≠ e → bottom i = 1)
    (havailability : (protocol * bottom) • R = bottom • S)
    (hleaf : ∃ σ ∈ zSub (M := ∀ j, Γ j) tupleGamma ({e} : Set I),
      protocol • R = σ • S) :
    ConstructsForAdversaryStructure (singleDishonest e) (protocol * bottom)
      (fun Z => zStar (M := ∀ j, Γ j) tupleGamma Z ({R} : Set Φ))
      (fun Z => zStar (M := ∀ j, Γ j) tupleGamma Z
        ({patternAttach Zᶜ bottom • S} : Set Φ)) := by
  have hprot := patternAttach_compl_singleton_eq_self (Γ := Γ) hprotocol
  have hbotOne := patternAttach_compl_singleton_eq_one (Γ := Γ) hbottom
  intro Z
  by_cases hZ : Z ∈ (singleDishonest e).sets
  · simp only [if_pos hZ]
    rcases Set.subset_singleton_iff_eq.mp hZ with rfl | rfl
    · rw [Set.compl_empty, zStar_empty, zStar_empty, patternAttach_univ,
        patternAttach_univ]
      exact constructs_singleton_iff.mpr havailability
    · obtain ⟨σ, hσ, heq⟩ := hleaf
      rw [patternAttach_mul, hprot, hbotOne, mul_one, one_smul]
      have hstep :=
        constructs_zStar_of_leaf (Z := ({e} : Set I)) (Γ := Γ) (Φ := Φ)
          (assumed := ({R} : Set Φ)) (ideal := S) protocol
          (fun R' hR' => by
            rw [Set.mem_singleton_iff] at hR'
            subst hR'
            exact ⟨σ, hσ, by rw [hprot]; exact heq⟩)
      rw [hprot] at hstep
      exact hstep
  · simp only [if_neg hZ]
    exact fun x _ => Set.mem_univ x

open Classical in
/-- The `ε`-relaxation applied to a finished specification family, over an
arbitrary adversary structure.  Weakening only: an exact construction is an
`ε`-approximate one for every radius. -/
theorem constructsForAdversaryStructure_eball_of_exact
    [PseudoEMetricSpace Φ] {𝒵 : AdversaryStructure I} {π : ∀ i, Γ i}
    {assumed ideal : Set I → Set Φ} (ε : ℝ≥0∞)
    (h : ConstructsForAdversaryStructure 𝒵 π assumed ideal) :
    ConstructsForAdversaryStructure 𝒵 π assumed
      (fun Z => Relaxation.eball ε (ideal Z)) := by
  intro Z
  have hz := h Z
  by_cases hZ : Z ∈ 𝒵.sets
  · simp only [if_pos hZ] at hz ⊢
    exact hz.mono subset_rfl ((Relaxation.eball ε).le_toFun _)
  · simp only [if_neg hZ]
    exact fun x _ => Set.mem_univ x

open Classical in
/-- **The LiuMau20 specification-form construction, from its two `ε`-close
leaves.**  The metric shape needed by the statistical endpoints: an endpoint
proves the availability bound and one `ε`-close simulator leaf, and gets
Definition 1's family over the adversary structure generated by `{e}` —
assumed and ideal both `∗Z`-relaxed, no simulator named in the statement.

`hprotocol` and `hbottom` are the interface-disjointness side conditions
MauRen11 leaves implicit: the protocol does nothing at the dishonest
interface, the availability filter does nothing anywhere else. -/
theorem constructsForAdversaryStructure_of_leaves
    [PseudoEMetricSpace Φ] [IsNonexpandingSMul (∀ i, Γ i) Φ]
    {e : I} {protocol bottom : ∀ i, Γ i} {ε : ℝ≥0∞} {R S : Φ}
    (hprotocol : protocol e = 1)
    (hbottom : ∀ i, i ≠ e → bottom i = 1)
    (havailability : edist ((protocol * bottom) • R) (bottom • S) ≤ ε)
    (hleaf : ∃ σ ∈ zSub (M := ∀ j, Γ j) tupleGamma ({e} : Set I),
      edist (protocol • R) (σ • S) ≤ ε) :
    ConstructsForAdversaryStructure (singleDishonest e) (protocol * bottom)
      (fun Z => zStar (M := ∀ j, Γ j) tupleGamma Z ({R} : Set Φ))
      (fun Z => Relaxation.eball ε
        (zStar (M := ∀ j, Γ j) tupleGamma Z
          ({patternAttach Zᶜ bottom • S} : Set Φ))) := by
  have hprot := patternAttach_compl_singleton_eq_self (Γ := Γ) hprotocol
  have hbotOne := patternAttach_compl_singleton_eq_one (Γ := Γ) hbottom
  intro Z
  by_cases hZ : Z ∈ (singleDishonest e).sets
  · simp only [if_pos hZ]
    rcases Set.subset_singleton_iff_eq.mp hZ with rfl | rfl
    · rw [Set.compl_empty, zStar_empty, zStar_empty, patternAttach_univ,
        patternAttach_univ]
      exact constructs_singleton_eball_iff.mpr havailability
    · obtain ⟨σ, hσ, hd⟩ := hleaf
      rw [patternAttach_mul, hprot, hbotOne, mul_one, one_smul]
      have hstep :=
        constructs_zStar_eps_of_leaf (Z := ({e} : Set I)) (Γ := Γ) (Φ := Φ)
          (assumed := ({R} : Set Φ)) (ideal := S) (ε := ε) protocol
          (fun R' hR' => by
            rw [Set.mem_singleton_iff] at hR'
            subst hR'
            exact ⟨σ, hσ, by rw [hprot]; exact hd⟩)
      rw [hprot] at hstep
      exact hstep
  · simp only [if_neg hZ]
    exact fun x _ => Set.mem_univ x

open Classical in
/-- **Fixed-`Z` ⟹ specification form.**  Every existing
`CC.SecurelyConstructs` endpoint at a singleton dishonest set lifts to the
LiuMau20 family, at the cost of the two interface-support side conditions and
one inclusion of the endpoint's admitted simulator class into the joint
dishonest class. -/
theorem constructsForAdversaryStructure_of_securelyConstructs
    [PseudoEMetricSpace Φ] [IsNonexpandingSMul (∀ i, Γ i) Φ]
    {e : I} {simulators : Submonoid (∀ i, Γ i)}
    {protocol bottom : ∀ i, Γ i} {ε : ℝ≥0∞} {R S : Φ}
    (hprotocol : protocol e = 1)
    (hbottom : ∀ i, i ≠ e → bottom i = 1)
    (hsimulators : simulators ≤ zSub (M := ∀ j, Γ j) tupleGamma ({e} : Set I))
    (h : CC.SecurelyConstructs ({e} : Set I) simulators protocol bottom ε R S) :
    ConstructsForAdversaryStructure (singleDishonest e) (protocol * bottom)
      (fun Z => zStar (M := ∀ j, Γ j) tupleGamma Z ({R} : Set Φ))
      (fun Z => Relaxation.eball ε
        (zStar (M := ∀ j, Γ j) tupleGamma Z
          ({patternAttach Zᶜ bottom • S} : Set Φ))) := by
  obtain ⟨havailability, σ, hσ, hsecurity⟩ := h
  rw [patternAttach_compl_singleton_eq_self (Γ := Γ) hprotocol,
    patternAttach_singleton_eq_self (Γ := Γ) hbottom, ← mul_smul] at havailability
  rw [patternAttach_compl_singleton_eq_self (Γ := Γ) hprotocol] at hsecurity
  exact constructsForAdversaryStructure_of_leaves hprotocol hbottom havailability
    ⟨σ, hsimulators hσ, hsecurity⟩

open Classical in
/-- **Specification form ⟹ fixed-`Z`** — the receipt that the migration loses
nothing.  The `Z = ∅` rung returns Definition 3's availability clause and the
`Z = {e}` rung returns its security clause, with the joint dishonest class as
the admitted simulator class. -/
theorem securelyConstructs_of_constructsForAdversaryStructure
    [PseudoEMetricSpace Φ]
    {e : I} {protocol bottom : ∀ i, Γ i} {ε : ℝ≥0∞} {R S : Φ}
    (hprotocol : protocol e = 1)
    (hbottom : ∀ i, i ≠ e → bottom i = 1)
    (h : ConstructsForAdversaryStructure (singleDishonest e) (protocol * bottom)
      (fun Z => zStar (M := ∀ j, Γ j) tupleGamma Z ({R} : Set Φ))
      (fun Z => Relaxation.eball ε
        (zStar (M := ∀ j, Γ j) tupleGamma Z
          ({patternAttach Zᶜ bottom • S} : Set Φ)))) :
    CC.SecurelyConstructs ({e} : Set I)
      (zSub (M := ∀ j, Γ j) tupleGamma ({e} : Set I)) protocol bottom ε R S := by
  have hprot := patternAttach_compl_singleton_eq_self (Γ := Γ) hprotocol
  have hbotSelf := patternAttach_singleton_eq_self (Γ := Γ) hbottom
  have hbotOne := patternAttach_compl_singleton_eq_one (Γ := Γ) hbottom
  constructor
  · have h0 := h ∅
    simp only [if_pos (empty_mem_singleDishonest e), Set.compl_empty, zStar_empty,
      patternAttach_univ] at h0
    have hedist := constructs_singleton_eball_iff.mp h0
    rw [hprot, hbotSelf, ← mul_smul]
    exact hedist
  · have h1 := h ({e} : Set I)
    simp only [if_pos (singleton_mem_singleDishonest e), patternAttach_mul, hprot,
      hbotOne, mul_one, one_smul] at h1
    have hmem : protocol • R ∈
        Relaxation.eball ε
          (zStar (M := ∀ j, Γ j) tupleGamma ({e} : Set I) ({S} : Set Φ)) :=
      h1 (Set.smul_mem_smul_set
        ((zStar (M := ∀ j, Γ j) tupleGamma ({e} : Set I)).le_toFun _ rfl))
    obtain ⟨y, hy, hd⟩ := Relaxation.mem_eball_iff.mp hmem
    obtain ⟨σ, hσ, s, hs, rfl⟩ := hy
    rw [Set.mem_singleton_iff] at hs
    subst hs
    exact ⟨σ, hσ, by rw [hprot]; exact hd⟩

end RandomSystemsCC
