/-
Copyright (c) 2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import RandomSystems.TypedAction
import RandomSystems.SemanticRegistry
import CC

/-!
# Full finite-interface random-systems instance of Abstract Cryptography

This module is the AC-facing boundary of the native dependent random-systems
model.  Pure RS supplies the heterogeneous behavioral resource carrier and
arbitrary stateful causal interface primitives.  Here those primitives
generate one *syntactic* converter monoid per interface — words over the
primitives modulo the serial monoid laws only, the paper's Γ — interpreted
into non-expanding endomorphisms by a homomorphism; the pairwise-commuting
interpretations combine into the exact indexed action required by the
selected AC contract.

No fixed global input/output alphabet is exposed publicly, no converter is
restricted to one query or to a memoryless map, and no application-specific
construction is involved.
-/

namespace RandomSystemsCC.TypedFinite

open AbstractCrypto
open RandomSystems.CR18
open RandomSystems.CR18.TypedResource
open scoped AbstractCrypto

universe c i u v

variable {I : Type i} {U : SignatureUniverse}
variable [DecidableEq I] [DecidableEq U.Code]

/-- AC's resource carrier: all behavioral dependent-system fibres, with
infinite distance between unequal boundaries. -/
abbrev Phi (I : Type i) (U : SignatureUniverse)
    [DecidableEq I] [DecidableEq U.Code] := Resource I U

namespace Primitive

/-- An arbitrary stateful deterministic causal primitive as AC's canonical
non-expanding endomorphism. -/
noncomputable def toNonexpandingEnd {interface : I}
    (primitive : Primitive I U interface) :
    nonexpandingEnd (Phi I U) :=
  ⟨primitive.act, primitive.act_lipschitz_with_one⟩

@[simp]
theorem to_nonexpanding_end_apply {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    (Primitive.toNonexpandingEnd primitive).val resource =
      primitive.act resource :=
  rfl

end Primitive

/-- Primitive actions localized at one interface. -/
noncomputable def primitiveRange (interface : I) :
    Set (nonexpandingEnd (Phi I U)) :=
  Set.range (Primitive.toNonexpandingEnd (I := I) (U := U)
    (interface := interface))

/-- The extensional submonoid of the ambient endomorphisms generated by every
arbitrary-stateful deterministic causal primitive at `i`.  This is the
*interpretation image* of the syntactic converter monoid `Gamma`
(`mrange_gammaInclusion_eq_generatedConverterMonoid`), not the converter type
itself: MauRen11's Γ is a set of programs closed under composition, never a
quotient by behavior, and identifying action-equal programs is exactly what
forecloses a representation-independent parallel operator (fn. 23). -/
noncomputable def generatedConverterMonoid (interface : I) :
    Submonoid (nonexpandingEnd (Phi I U)) :=
  Submonoid.closure (primitiveRange (I := I) (U := U) interface)

/-- Converter words at one interface: the free serial `{1, ∘}`-algebra over
the arbitrary stateful deterministic causal primitives at `i` — the paper's
constructor set, as syntax. -/
inductive ConverterTerm (I : Type i) (U : SignatureUniverse.{c, u, v})
    [DecidableEq I] [DecidableEq U.Code] (interface : I) :
    Type (max c u v)
  | prim (primitive : Primitive I U interface)
  | one
  | mul (left right : ConverterTerm I U interface)

namespace ConverterTerm

/-- Interpretation of a converter word as AC's canonical non-expanding
endomorphism: a primitive acts natively and serial composition is
endomorphism composition (right factor first). -/
noncomputable def eval {interface : I} :
    ConverterTerm I U interface → nonexpandingEnd (Phi I U)
  | prim primitive => Primitive.toNonexpandingEnd primitive
  | one => 1
  | mul left right => left.eval * right.eval

/-- The code a converter word leaves at its interface, given the code it
starts from; `none` as soon as one factor's source fails to match what the
previous factor produced.  `mul left right` runs `right` first, exactly as
`eval` does.  This is the syntactic well-typedness judgment on words that the
extensional Γ could not express: it is definable only because `Gamma` is a
quotient of syntax by the monoid laws alone (`outCode_congr`). -/
def outCode {interface : I} :
    ConverterTerm I U interface → U.Code → Option U.Code
  | prim primitive, code =>
      if code = primitive.source then some primitive.target else none
  | one, code => some code
  | mul left right, code => (outCode right code).bind (outCode left)

/-- A converter word is well placed on a starting code when every factor's
source matches what the previous factor produced.  On a mismatched word the
total action silently skips the offending factor (`Primitive.act` is the
identity off its source code), so the word's protocol label lies about what
acted; a construction statement must carry this obligation, and
`boundary_eval_of_outCode` is the receipt it buys. -/
def WellPlaced {interface : I} (word : ConverterTerm I U interface)
    (code : U.Code) : Prop :=
  (outCode word code).isSome

/-- The monoid-law congruence on converter words: associativity and the two
unit laws for serial composition, closed under composition.  Nothing else —
in particular no behavioral identification. -/
inductive Rel {interface : I} :
    ConverterTerm I U interface → ConverterTerm I U interface → Prop
  | refl (a) : Rel a a
  | symm {a b} : Rel a b → Rel b a
  | trans {a b c} : Rel a b → Rel b c → Rel a c
  | assoc (a b c) : Rel (mul (mul a b) c) (mul a (mul b c))
  | one_mul (a) : Rel (mul one a) a
  | mul_one (a) : Rel (mul a one) a
  | mul_congr {a a' b b'} : Rel a a' → Rel b b' → Rel (mul a b) (mul a' b')

theorem eval_congr {interface : I} {a b : ConverterTerm I U interface}
    (h : Rel a b) : a.eval = b.eval := by
  induction h with
  | refl a => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | assoc a b c => exact mul_assoc _ _ _
  | one_mul a => exact one_mul _
  | mul_one a => exact mul_one _
  | mul_congr _ _ ih₁ ih₂ =>
      show _ * _ = _ * _
      rw [ih₁, ih₂]

/-- `outCode` respects the monoid-law congruence, so well-placedness is a
property of the *converter*, not of a representative: associativity is
`Option.bind_assoc` and the unit laws are the two `bind`/`some` identities. -/
theorem outCode_congr {interface : I} {a b : ConverterTerm I U interface}
    (h : Rel a b) : a.outCode = b.outCode := by
  induction h with
  | refl a => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | assoc a b c => funext code; simp [outCode, Option.bind_assoc]
  | one_mul a => funext code; simp [outCode]
  | mul_one a => funext code; simp [outCode]
  | mul_congr _ _ ih₁ ih₂ => funext code; simp [outCode, ih₁, ih₂]

instance setoid (interface : I) : Setoid (ConverterTerm I U interface) :=
  ⟨Rel, ⟨Rel.refl, Rel.symm, Rel.trans⟩⟩

/-- Serial words at distinct interfaces commute after interpretation: exact
primitive commutation extends through the word structure. -/
theorem eval_commute {leftInterface rightInterface : I}
    (different : leftInterface ≠ rightInterface)
    (left : ConverterTerm I U leftInterface)
    (right : ConverterTerm I U rightInterface) :
    Commute left.eval right.eval := by
  induction left with
  | prim leftPrimitive =>
      induction right with
      | prim rightPrimitive =>
          apply Subtype.ext
          funext resource
          exact leftPrimitive.act_comm different rightPrimitive resource
      | one => exact Commute.one_right _
      | mul _ _ commute₁ commute₂ => exact commute₁.mul_right commute₂
  | one => exact Commute.one_left _
  | mul _ _ commute₁ commute₂ => exact commute₁.mul_left commute₂

/-- **The well-placedness receipt**: a word whose `outCode` accepts the
resource's local code moves the boundary exactly as its type says.  This is
the statement-level cure for the silent-identity default of `Primitive.act`:
the action stays total (metrically harmless, since its guard is
code-determined and `boundaryEdist` separates codes at `⊤`), and the
truthfulness of a protocol label is recovered as this proof obligation. -/
theorem boundary_eval_of_outCode {interface : I}
    (word : ConverterTerm I U interface) (resource : Phi I U)
    {target : U.Code}
    (accepted : outCode word (resource.boundary interface) = some target) :
    ((eval word).val resource).boundary =
      replaceBoundary resource.boundary interface target := by
  induction word generalizing resource target with
  | prim primitive =>
      rcases resource with ⟨boundary, system⟩
      simp only [outCode] at accepted
      split at accepted
      · obtain rfl : primitive.target = target := Option.some.inj accepted
        calc ((eval (prim primitive)).val ⟨boundary, system⟩).boundary
            = (primitive.act ⟨boundary, system⟩).boundary := rfl
          _ = replaceBoundary boundary interface primitive.target := by
              rw [Primitive.act_of_matches primitive boundary
                (by assumption) system]
      · exact absurd accepted (by simp)
  | one =>
      simp only [outCode, Option.some.injEq] at accepted
      subst accepted
      exact (Function.update_eq_self interface resource.boundary).symm
  | mul left right leftIH rightIH =>
      simp only [outCode] at accepted
      obtain ⟨middle, rightAccepted, leftAccepted⟩ :=
        Option.bind_eq_some_iff.mp accepted
      have rightBoundary := rightIH resource rightAccepted
      have leftBoundary := leftIH ((eval right).val resource)
        (by rw [rightBoundary, replace_boundary_same]; exact leftAccepted)
      calc ((eval (mul left right)).val resource).boundary
          = ((eval left).val ((eval right).val resource)).boundary := rfl
        _ = replaceBoundary ((eval right).val resource).boundary interface
              target := leftBoundary
        _ = replaceBoundary resource.boundary interface target := by
              rw [rightBoundary]
              simp only [replaceBoundary, Function.update_idem]

end ConverterTerm

/-- The actual indexed converter family consumed by AC: converter words at
`i` modulo the serial monoid laws only — the paper's syntactic Γᵢ.  AC's
contract asks for a monoid with an action, not for extensionality; the
quotient by action-equality that used to live here is unsound for a future
parallel operator (MauRen11 fn. 23) and is deliberately absent. -/
def Gamma (I : Type i) (U : SignatureUniverse.{c, u, v})
    [DecidableEq I] [DecidableEq U.Code] (interface : I) : Type (max c u v) :=
  Quotient (ConverterTerm.setoid (I := I) (U := U) interface)

/-- AC protocol tuples, one converter program per interface. -/
abbrev Protocol (I : Type i) (U : SignatureUniverse)
    [DecidableEq I] [DecidableEq U.Code] :=
  ∀ interface : I, Gamma I U interface

namespace Gamma

/-- Display a converter word. -/
def mk {interface : I} (a : ConverterTerm I U interface) :
    Gamma I U interface :=
  Quotient.mk (ConverterTerm.setoid interface) a

instance {interface : I} : One (Gamma I U interface) :=
  ⟨mk ConverterTerm.one⟩

instance {interface : I} : Mul (Gamma I U interface) :=
  ⟨Quotient.map₂ ConverterTerm.mul
    (fun _ _ ha _ _ hb => ConverterTerm.Rel.mul_congr ha hb)⟩

@[simp]
theorem mk_mul {interface : I} (a b : ConverterTerm I U interface) :
    mk a * mk b = mk (ConverterTerm.mul a b) :=
  rfl

instance instMonoid {interface : I} : Monoid (Gamma I U interface) where
  mul_assoc a b c := by
    induction a using Quotient.inductionOn with
    | _ a =>
        induction b using Quotient.inductionOn with
        | _ b =>
            induction c using Quotient.inductionOn with
            | _ c => exact Quot.sound (ConverterTerm.Rel.assoc a b c)
  one_mul a := by
    induction a using Quotient.inductionOn with
    | _ a => exact Quot.sound (ConverterTerm.Rel.one_mul a)
  mul_one a := by
    induction a using Quotient.inductionOn with
    | _ a => exact Quot.sound (ConverterTerm.Rel.mul_one a)

/-- Interpretation: the underlying non-expanding endomorphism of a converter
word — the value AC's action consumes.  Named `val` so that action statements
read exactly as under the former extensional presentation. -/
noncomputable def val {interface : I} :
    Gamma I U interface → nonexpandingEnd (Phi I U) :=
  Quotient.lift ConverterTerm.eval fun _ _ h => ConverterTerm.eval_congr h

@[simp]
theorem val_mk {interface : I} (a : ConverterTerm I U interface) :
    (mk a).val = a.eval :=
  rfl

@[simp]
theorem val_one {interface : I} : (1 : Gamma I U interface).val = 1 :=
  rfl

@[simp]
theorem val_mul {interface : I} (a b : Gamma I U interface) :
    (a * b).val = a.val * b.val := by
  induction a using Quotient.inductionOn with
  | _ a =>
      induction b using Quotient.inductionOn with
      | _ b => rfl

/-- The code a converter leaves at its interface, descended from words: the
`Rel` descent (`ConverterTerm.outCode_congr`) is what makes well-placedness a
property of the converter rather than of a representative. -/
def outCode {interface : I} :
    Gamma I U interface → U.Code → Option U.Code :=
  Quotient.lift ConverterTerm.outCode
    fun _ _ h => ConverterTerm.outCode_congr h

@[simp]
theorem outCode_mk {interface : I} (a : ConverterTerm I U interface) :
    (mk a).outCode = a.outCode :=
  rfl

@[simp]
theorem outCode_one {interface : I} (code : U.Code) :
    (1 : Gamma I U interface).outCode code = some code :=
  rfl

@[simp]
theorem outCode_mul {interface : I} (a b : Gamma I U interface)
    (code : U.Code) :
    (a * b).outCode code = (b.outCode code).bind a.outCode := by
  induction a using Quotient.inductionOn with
  | _ a =>
      induction b using Quotient.inductionOn with
      | _ b => rfl

/-- A converter is well placed on a starting code when some (equivalently,
every) representative word is. -/
def WellPlaced {interface : I} (converter : Gamma I U interface)
    (code : U.Code) : Prop :=
  (converter.outCode code).isSome

theorem wellPlaced_mk {interface : I} (a : ConverterTerm I U interface)
    (code : U.Code) :
    (mk a).WellPlaced code ↔ a.WellPlaced code :=
  Iff.rfl

/-- The well-placedness receipt on the converter quotient: an accepted
converter moves the boundary exactly as its type says. -/
theorem boundary_val_of_outCode {interface : I}
    (converter : Gamma I U interface) (resource : Phi I U)
    {target : U.Code}
    (accepted : converter.outCode (resource.boundary interface) =
      some target) :
    (converter.val.val resource).boundary =
      replaceBoundary resource.boundary interface target := by
  induction converter using Quotient.inductionOn with
  | _ word => exact ConverterTerm.boundary_eval_of_outCode word resource accepted

end Gamma

/-- Insert one primitive into its interface's converter monoid. -/
@[rs_rule "rs.typed.converter_of_primitive" rs_typed_converter random_systems]
def Gamma.ofPrimitive {interface : I}
    (primitive : Primitive I U interface) : Gamma I U interface :=
  Gamma.mk (ConverterTerm.prim primitive)

@[simp]
theorem Gamma.of_primitive_apply {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    (Gamma.ofPrimitive primitive).val.val resource = primitive.act resource :=
  rfl

@[simp]
theorem Gamma.outCode_ofPrimitive {interface : I}
    (primitive : Primitive I U interface) (code : U.Code) :
    (Gamma.ofPrimitive primitive).outCode code =
      if code = primitive.source then some primitive.target else none :=
  rfl

/-- The syntactic converter monoids at distinct interfaces commute after
interpretation in the ambient endomorphism monoid. -/
theorem gamma_commute {leftInterface rightInterface : I}
    (different : leftInterface ≠ rightInterface)
    (left : Gamma I U leftInterface)
    (right : Gamma I U rightInterface) :
    Commute left.val right.val := by
  induction left using Quotient.inductionOn with
  | _ left =>
      induction right using Quotient.inductionOn with
      | _ right => exact ConverterTerm.eval_commute different left right

/-- Interpretation of the interface-`i` converter monoid into all
non-expanding resource endomorphisms — the homomorphism `⟦·⟧` through which
the AC action factors. -/
noncomputable def gammaInclusion (interface : I) :
    Gamma I U interface →* nonexpandingEnd (Phi I U) where
  toFun := Gamma.val
  map_one' := rfl
  map_mul' := Gamma.val_mul

/-- Interpretation-membership induction: a submonoid of the ambient
endomorphisms containing every primitive action at `i` contains the whole
interpreted converter monoid.  This is the syntactic replacement for
`Submonoid.closure_induction` under the former extensional Γ. -/
theorem gammaInclusion_mem_of_forall_primitive_mem {interface : I}
    {S : Submonoid (nonexpandingEnd (Phi I U))}
    (primitiveMember :
      ∀ primitive : Primitive I U interface,
        Primitive.toNonexpandingEnd primitive ∈ S)
    (converter : Gamma I U interface) :
    gammaInclusion interface converter ∈ S := by
  induction converter using Quotient.inductionOn with
  | _ converter =>
      induction converter with
      | prim primitive => exact primitiveMember primitive
      | one => exact one_mem S
      | mul left right leftMember rightMember =>
          exact mul_mem leftMember rightMember

/-- The extensional generated monoid is exactly the interpretation image of
the syntactic converter monoid: the representation-forgetting receipt that
relates the two presentations. -/
theorem mrange_gammaInclusion_eq_generatedConverterMonoid (interface : I) :
    MonoidHom.mrange (gammaInclusion (I := I) (U := U) interface) =
      generatedConverterMonoid interface := by
  refine le_antisymm ?_ (Submonoid.closure_le.mpr ?_)
  · rintro _ ⟨converter, rfl⟩
    exact gammaInclusion_mem_of_forall_primitive_mem
      (fun primitive =>
        Submonoid.subset_closure (Set.mem_range_self primitive))
      converter
  · rintro _ ⟨primitive, rfl⟩
    exact ⟨Gamma.ofPrimitive primitive, rfl⟩

/-- The commuting family of inclusions combines every converter tuple into
one non-expanding endomorphism. -/
noncomputable def protocolEndHom [Fintype I] :
    Protocol I U →* nonexpandingEnd (Phi I U) :=
  MonoidHom.noncommPiCoprod (gammaInclusion (I := I) (U := U))
    (fun leftInterface rightInterface different left right =>
      gamma_commute (leftInterface := leftInterface)
        (rightInterface := rightInterface) different left right)

/-- The selected current-AC indexed action.  This is a genuine action of
`(∀ i, Γ i)` on one heterogeneous resource carrier `Φ`. -/
noncomputable instance instMulAction [Fintype I] :
    MulAction (Protocol I U) (Phi I U) :=
  MulAction.compHom (Phi I U)
    ((Submonoid.subtype (nonexpandingEnd (Phi I U))).comp
      (protocolEndHom (I := I) (U := U)))

/-- The tuple action is non-expanding because its image lies in AC's
`nonexpandingEnd` monoid. -/
instance instIsNonexpandingSMul [Fintype I] :
    IsNonexpandingSMul (Protocol I U) (Phi I U) where
  lipschitz_smul protocol :=
    (protocolEndHom (I := I) (U := U) protocol).property

/-- A singleton-supported tuple performs exactly the represented
single-interface converter action. -/
theorem mul_single_smul [Fintype I] (interface : I)
    (converter : Gamma I U interface) (resource : Phi I U) :
    (Pi.mulSingle interface converter : Protocol I U) • resource =
      converter.val.val resource := by
  change (protocolEndHom (I := I) (U := U)
      (Pi.mulSingle interface converter)).val resource = _
  unfold protocolEndHom
  rw [MonoidHom.noncommPiCoprod_mulSingle]
  rfl

/-- The well-placedness receipt at the AC protocol surface, generalizing the
by-hand single-primitive boundary checks: a singleton-supported tuple whose
converter is accepted at the resource's local code has exactly the advertised
boundary. -/
theorem boundary_mul_single_smul_of_outCode [Fintype I] {interface : I}
    (converter : Gamma I U interface) (resource : Phi I U)
    {target : U.Code}
    (accepted : converter.outCode (resource.boundary interface) =
      some target) :
    ((Pi.mulSingle interface converter : Protocol I U) • resource).boundary =
      replaceBoundary resource.boundary interface target := by
  rw [mul_single_smul]
  exact converter.boundary_val_of_outCode resource accepted

/-- A local converter at its own interface, embedded as an AC protocol —
the paper's `αⁱ` (`Pi.mulSingle i (Gamma.ofPrimitive ·)`).  You should never
write this by hand: it is the target of the `Coe` and `SMul` instances just
below, which make a bare `Primitive` usable directly with `•` and `—[·]→`. -/
noncomputable def protocolOfPrimitive {interface : I}
    (primitive : Primitive I U interface) : Protocol I U :=
  Pi.mulSingle interface (Gamma.ofPrimitive primitive)

/-- **Automated lifting (coercion).**  A local converter *is* a protocol
(identity off its interface), so a `Primitive` appears directly wherever a
`Protocol` is expected — in particular in the construction notation
`⟪R⟫ —[flip]→ …`.  The embedding fires automatically; you write `flip`. -/
noncomputable instance {interface : I} :
    CoeTC (Primitive I U interface) (Protocol I U) :=
  ⟨protocolOfPrimitive⟩

/-- **Automated lifting (native action).**  A local converter acts on
resources directly, `p • R := p.act R`, so `flip • R` reads as algebra with
no embedding written. -/
noncomputable instance {interface : I} :
    SMul (Primitive I U interface) (Phi I U) :=
  ⟨fun p R => p.act R⟩

@[simp] theorem primitive_smul_eq_act {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    primitive • resource = primitive.act resource :=
  rfl

/-- The generic primitive receipt: AC notation exposes precisely native typed
attachment at the selected interface. -/
theorem primitive_mul_single_smul [Fintype I] {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    (Pi.mulSingle interface (Gamma.ofPrimitive primitive) : Protocol I U) •
        resource =
      primitive.act resource := by
  rw [mul_single_smul]
  rfl

/-- **The two liftings agree**: applying the coerced protocol equals the
native converter action, `(↑p) • R = p • R`.  This is what lets an AC
construction statement about `↑p` be discharged from the native RS action —
the bridge is a `simp` lemma, invisible in use. -/
@[simp] theorem coe_primitive_smul [Fintype I] {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    (protocolOfPrimitive primitive) • resource = primitive • resource := by
  rw [primitive_smul_eq_act]
  exact primitive_mul_single_smul primitive resource

/-- **Automated lifting (construction notation).**  A bare `Primitive` is
usable in a construction statement, `⟪R⟫ —[flip]→ ⟪S⟫`, delegating to the
AC construction of its embedding.  The tuple/monoid embedding never appears
in the statement. -/
noncomputable instance [Fintype I] {interface : I} :
    HasReduction (Set (Phi I U)) (Primitive I U interface) where
  Red R primitive S := R —[protocolOfPrimitive primitive]→ S

/-- Serial composition at one interface is ordinary AC multiplication: the
right primitive acts first and the left primitive acts second.  This theorem
is representation-independent; products need not be re-encoded as one raw
protocol-function record. -/
theorem primitive_mul_smul [Fintype I] {interface : I}
    (outer inner : Primitive I U interface) (resource : Phi I U) :
    ((Pi.mulSingle interface (Gamma.ofPrimitive outer) : Protocol I U) *
        Pi.mulSingle interface (Gamma.ofPrimitive inner)) • resource =
      outer.act (inner.act resource) := by
  rw [mul_smul, primitive_mul_single_smul, primitive_mul_single_smul]

/-- A generic exact construction receipt over the fully instantiated AC
surface.  This is an integration test, not an application model. -/
@[rs_rule "rs.typed.constructs" ac_spec_construction random_systems]
theorem primitive_constructs [Fintype I] {interface : I}
    (primitive : Primitive I U interface) (resource : Phi I U) :
    ({resource} : Set (Phi I U))
      —[Pi.mulSingle interface (Gamma.ofPrimitive primitive)]→
    ({primitive.act resource} : Set (Phi I U)) := by
  exact constructs_singleton_iff.mpr
    (primitive_mul_single_smul primitive resource)

/-! ## Header-free configured models -/

/-- A finite typed RS model packages the ambient interface and signature
choices once.  Downstream theorems quantify over `model.Phi`,
`model.Gamma i`, and `model.Protocol`; they do not repeat the implementation
instances or AC's monoid/action/metric headers. -/
structure Model where
  Interface : Type i
  signatures : SignatureUniverse.{c, u, v}
  finiteInterface : Fintype Interface
  interfaceDecidableEq : DecidableEq Interface
  codeDecidableEq : DecidableEq signatures.Code

namespace Model

variable (model : Model.{c, i, u, v})

/-- The configured resource carrier. -/
abbrev Phi : Type _ :=
  @RandomSystemsCC.TypedFinite.Phi model.Interface model.signatures
    model.interfaceDecidableEq model.codeDecidableEq

/-- The configured converter monoid at one interface. -/
abbrev Gamma (interface : model.Interface) : Type _ :=
  @RandomSystemsCC.TypedFinite.Gamma model.Interface model.signatures
    model.interfaceDecidableEq model.codeDecidableEq interface

/-- The configured AC protocol type. -/
abbrev Protocol : Type _ := ∀ interface, model.Gamma interface

noncomputable instance instPseudoEMetricSpace :
    PseudoEMetricSpace model.Phi := by
  letI : DecidableEq model.Interface := model.interfaceDecidableEq
  letI : DecidableEq model.signatures.Code := model.codeDecidableEq
  infer_instance

noncomputable instance instMulAction :
    MulAction model.Protocol model.Phi := by
  letI : Fintype model.Interface := model.finiteInterface
  letI : DecidableEq model.Interface := model.interfaceDecidableEq
  letI : DecidableEq model.signatures.Code := model.codeDecidableEq
  exact RandomSystemsCC.TypedFinite.instMulAction

noncomputable instance instIsNonexpandingSMul :
    IsNonexpandingSMul model.Protocol model.Phi := by
  letI : Fintype model.Interface := model.finiteInterface
  letI : DecidableEq model.Interface := model.interfaceDecidableEq
  letI : DecidableEq model.signatures.Code := model.codeDecidableEq
  exact RandomSystemsCC.TypedFinite.instIsNonexpandingSMul

end Model

end RandomSystemsCC.TypedFinite
